server:
  port: 8099
spring:
  application:
    name: ceshi-servicecui-1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cui?useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #ip: 10.72.232.232
  devtools:
    restart:
      enabled: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
mybatis:
   mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml
   configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
sqlhelper:
  mybatis:
    instrumentor:
      #神通数据库目前暂时需要配置该选项，方便兼容神通的模式
      dialect: postgresql